name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'
      - 'code-style.yml'

jobs:
  code-style:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@1.0.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
