name: Unit test coverage

on:
  - push
  - pull_request

jobs:
  coverage:
    if: (github.repository == 'laravel-notification-channels/telegram') && "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "latest"
          coverage: pcov

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist"

      - name: Execute tests
        run: vendor/bin/pest --coverage --coverage-clover build/pest.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/pest.xml
          verbose: true
