name: Code Style

on: [push]

jobs:
  phplint:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: "Laravel Pint"
        uses: aglipanci/laravel-pint-action@1.0.0
        with:
          preset: laravel
          
      - name: Commit changes to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "PHP Style Change (Laravel Pint in CI)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
