name: PHPUnit tests

on:
  - push
  - pull_request

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: true
      matrix:
        php: ['8.1', '8.2', '8.3']
        dependencies: [lowest, highest]
        experimental: [false]

    name: PHP ${{ matrix.php }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist ${{ matrix.composer-options }}

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: ./vendor/bin/pest
